import { SC2Error } from '../errors.js';

export interface GalaxyEntrypoint {
  readonly libraryPath: string;
  readonly includePath: string;
  readonly initFunction: string;
  readonly content: string;
}

/**
 * Renders the smallest MapScript that loads NativeLib, includes one authored library,
 * and delegates map setup to one initializer.
 *
 * This is intentionally narrower than a generated-script editor. Callers cannot inject
 * arbitrary snippets into MapScript, and the authored library remains independently
 * readable and syntax-checkable.
 */
export function renderGalaxyEntrypoint(libraryPath: string, initFunction: string): GalaxyEntrypoint {
  const normalizedPath = libraryPath.replaceAll('\\', '/');
  if (!normalizedPath.toLowerCase().endsWith('.galaxy')) {
    throw new SC2Error('SC2_INVALID_ARGUMENT', 'The entrypoint library must end in .galaxy.', {
      path: libraryPath,
      recoverable: true,
    });
  }
  if (normalizedPath.toLowerCase() === 'mapscript.galaxy') {
    throw new SC2Error('SC2_INVALID_ARGUMENT', 'MapScript.galaxy cannot include itself.', {
      path: libraryPath,
      recoverable: true,
    });
  }
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(initFunction)) {
    throw new SC2Error('SC2_INVALID_ARGUMENT', `Invalid Galaxy function name: ${initFunction}`, {
      recoverable: true,
    });
  }

  const includePath = normalizedPath.slice(0, -'.galaxy'.length);
  const content =
    '// Generated by sc2_set_galaxy_entrypoint. The Galaxy Editor may regenerate this file.\r\n' +
    'include "TriggerLibs/NativeLib"\r\n' +
    `include "${includePath}"\r\n` +
    '\r\n' +
    'void InitLibs () {\r\n' +
    '    libNtve_InitLib();\r\n' +
    '}\r\n' +
    '\r\n' +
    'void InitMap () {\r\n' +
    '    InitLibs();\r\n' +
    `    ${initFunction}();\r\n` +
    '}\r\n';

  return { libraryPath: normalizedPath, includePath, initFunction, content };
}
